
const adminTypes= {

    ADMIN_GET_BY_ID: 'ADMIN_GET_BY_ID',
    ADMIN_BALANCE: 'ADMIN_BALANCE',
    DEPOSIT: 'DEPOSIT',
    ADMIN_ERROR: 'ADMIN_ERROR',
    ADMIN_USER_TRANS_HIS: 'ADMIN_USER_TRANS',
    ADMIN_USER_DEPO_HIS: 'ADMIN_USER_DEPO_HIS',
    ALL_TRANS_HIS: 'ALL_TRANS_HIS',
    ALL_PAYMENT_HIS: 'ALL_PAYMENT_HIS',
    ADMIN_REGISTER: 'ADMIN_REGISTER',
    ALL_STUDENTS: 'ALL_STUDENTS',
    GET_USER_DETAILS: 'GET_USER_DETAILS',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    UPDATE: 'UPDATE',
    LOADING: 'LOADING'
}

export default adminTypes;