
const userTypes ={

    USER_LOADING: "USER_LOADING",
    USER_LOGIN: "USER_LOGIN",
    USER_DEPOSIT: "USER_DEPOSIT",
    USER_LOGOUT: "USER_LOGOUT",
    USER_DATA: "USER_DATA",
    USER_TRANSACTION_HIS: "USER_TRANSACTION_HIS",
    USER_PAYMENT_HIS: "USER_PAYMENT_HIS",
    USER_ERRORS: "USER_ERRORS",
    USER_AUTHENTICATE: "USER_AUTHENTICATE"
}

export default userTypes;


